name: 'Terraform CI/CD'

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
      - '.github/workflows/terraform.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'infra/**'
      - '.github/workflows/terraform.yml'

jobs:
  terraform:
    name: 'Terraform Automation'
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      HUGGING_FACE_API_TOKEN: ${{ secrets.HUGGING_FACE_API_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.11

      - name: Initialize Terraform
        working-directory: ./infra
        run: terraform init

      - name: Lint Terraform
        working-directory: ./infra
        run: terraform fmt -check

      - name: Validate Terraform
        working-directory: ./infra
        run: terraform validate

      - name: Plan Terraform
        working-directory: ./infra
        run: terraform plan

      - name: Apply Terraform
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        working-directory: ./infra
        run: terraform apply -auto-approve
